name: Deploy
on:
  push:
    branches:
      - master
jobs:  
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.github_token }}
        TARGET_REPO: innovolve-ai/typerefinery.ai
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: src/.vuepress/dist

    - name: Manually index site
      usess: docker://algolia/docsearch-scraper
      with:
        environment:
          CONFIG: "$(cat ./config.json | jq -r tostring)"
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
