name: Deploy
on:
  push:
    branches:
      - main
jobs:  
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production 
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: NPM Install
      run: npm install

    - name: NPM Build
      run: npm run build

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: src/.vuepress/dist

    - name: Wait for job "pages build and deployment" to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        check-name: 'pages-build-deployment'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 90
        
    - name: Get config
      run: |
        echo "CONFIG=$(cat ./config.json | jq -r tostring)" >> $GITHUB_ENV

    - name: Manually index site
      env:
        CONFIG: "${{ env.CONFIG }}"
        APPLICATION_ID: "${{ secrets.APPLICATION_ID }}:"
        API_KEY: "${{ secrets.API_KEY }}"
      run: docker run -e CONFIG -e APPLICATION_ID -e API_KEY algolia/docsearch-scraper 
