name: Build and Deploy
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:  
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: NPM Install
      run: npm install

    - name: Run Build
      run: npm run build
